services: 
  web: 
    image: nginx:latest 
    ports: 
      - "8080:80" 
    volumes: 
      - ./web:/usr/share/nginx/html 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on: 
      - php 
 
  php: 
    build: 
      context: . 
      dockerfile: Dockerfile
    volumes: 
      - ./web:/usr/share/nginx/html 
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reloj_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password  
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes: 
  db_data: